# Generated by Django 3.0.8 on 2020-09-16 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_servicescompleted'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicescompleted',
            options={'ordering': ['-date']},
        ),
    ]
