# Generated by Django 3.0.8 on 2020-09-17 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20200916_2326'),
    ]

    operations = [
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('winnings', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='shows',
            field=models.ManyToManyField(to='main_app.Show'),
        ),
    ]
