# Generated by Django 3.0.8 on 2020-09-17 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20200917_2105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='show',
            name='winnings',
        ),
    ]
